name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend:
    name: backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2.1.1
      with:
        go-version: 1.14
    - uses: actions/checkout@v2
    - run: make backend
  frontend:
    name: frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.7'
    - run: make frontend
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.7'
    - run: make frontend-build
    - run: mv out/public out/pr${{ github.event.number }}
    - uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
      with:
        credentials: ${{ secrets.gcp_credentials }}
        path: out/pr${{ github.event.number }}
        destination: triangulation31/covid19
