name: pr comment

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `On successful build preview at [covid19/pr${context.payload.pull_request.number}](https://storage.googleapis.com/triangulation31/covid19/pr${context.payload.pull_request.number}/index.html).`
            })

